services:
  build-linux:
    image: sergioeld/omnirefl-build-alpine
    build:
      context: .
      dockerfile: build-alpine.Dockerfile
    volumes:
      - ./:/src:ro
      - ./build-alpine/linux:/build:rw
    working_dir: /build
    entrypoint: ['/bin/ash', '-c']
    # todo: debug symbols should be available
    command: 
      - |
        cmake /src -GNinja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DENABLE_PACKAGE=ON \
          -DENABLE_TESTING=ON \
          -DClang_DIR=$${CLANG_INSTALL_LINUX}/lib/cmake/clang &&
        cmake --build . -t omnirefl -j$$(nproc) && # strip it before running tests 
        strip --strip-all omnirefl # set(CPACK_STRIP_FILES TRUE) doesn't work

  build-windows:
    image: sergioeld/omnirefl-build-alpine
    build:
      context: .
      dockerfile: build-alpine.Dockerfile
    volumes:
      - ./:/src:ro
      - ./build-alpine/windows:/build:rw
    working_dir: /build
    entrypoint: ['/bin/ash', '-c']
    # todo: debug symbols should be available
    # testing only possible in Windows container
    command: 
      - |
        CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ LDFLAGS=-static \
          cmake /src -GNinja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DENABLE_PACKAGE=ON \
          -DENABLE_TESTING=OFF \
          -DClang_DIR=$${CLANG_INSTALL_WINDOWS}/lib/cmake/clang &&
        cmake --build . -t omnirefl.exe -j$$(nproc) && # strip it before running tests 
        strip --strip-all omnirefl.exe # set(CPACK_STRIP_FILES TRUE) doesn't work

  build-tests-alpine:
    image: sergioeld/omnirefl-build-alpine
    volumes:
      - ./:/src:ro
      - ./build-alpine/linux:/build:rw
    working_dir: /build
    entrypoint: ['/bin/ash', '-c']
    command: 
      - |
        cmake --build . -j$$(nproc) &&
        mkdir -p /build/test/alpine &&
        ctest . --output-junit /build/test/alpine/results.xml \
          -V | tee /build/test/alpine/results.log

  package-linux:
    image: sergioeld/omnirefl-build-alpine
    volumes:
      - ./:/src:ro
      - ./build-alpine/linux:/build:rw
    working_dir: /build
    entrypoint: ['/bin/ash', '-c']
    # todo: specify a directory which is easy to upload as artifact
    command: 
      - |
        cpack -G "DEB;TGZ" &&
        mkdir -p /build/install &&
        mv *.deb *.tar.gz /build/install/

  package-windows:
    image: sergioeld/omnirefl-build-alpine
    volumes:
      - ./:/src:ro
      - ./build-alpine/windows:/build:rw
    working_dir: /build
    entrypoint: ['/bin/ash', '-c']
    # todo: specify a directory which is easy to upload as artifact
    command: 
      - |
        cpack -G "ZIP" &&
        mkdir -p /build/install &&
        mv *.zip /build/install/

  # todo: can I have a matrix for 18, 20, 22?
  test-ubuntu-18:
    image: sergioeld/test-install-ubuntu-18
    build:
      context: .
      dockerfile: test-install-ubuntu.Dockerfile
      args: 
        - UBUNTU_VERSION=18.04
    volumes:
      - ./build-alpine/linux/install:/install:ro
    working_dir: /install
    entrypoint: ['/bin/bash', '-c']
    command:
      - |
        apt install ./omnirefl*.deb &&
        mkdir -p /tmp/test/build && cd /tmp/test/build
        cp -r /usr/share/omnirefl/tests/* ../
        cmake .. -GNinja &&
        mkdir -p /build/test/ubuntu-18 &&
        ctest . --output-junit /build/test/ubuntu-18/results.xml \
          -V | tee /build/test/ubuntu-18/results.log \
        && apt remove -y omnirefl

  test-ubuntu-20:
    image: sergioeld/test-install-ubuntu-20
    build:
      context: .
      dockerfile: test-install-ubuntu.Dockerfile
      args: 
        - UBUNTU_VERSION=20.04
    volumes:
      - ./build-alpine/linux/install:/install:ro
    working_dir: /install
    entrypoint: ['/bin/bash', '-c']
    command:
      - |
        apt install ./omnirefl*.deb &&
        mkdir -p /tmp/test/build && cd /tmp/test/build
        cp -r /usr/share/omnirefl/tests/* ../
        cmake .. -GNinja &&
        mkdir -p /build/test/ubuntu-18 &&
        ctest . --output-junit /build/test/ubuntu-20/results.xml \
          -V | tee /build/test/ubuntu-20/results.log \
        && apt remove -y omnirefl

  test-ubuntu-22:
    image: sergioeld/test-install-ubuntu-22
    build:
      context: .
      dockerfile: test-install-ubuntu.Dockerfile
      args: 
        - UBUNTU_VERSION=22.04
    volumes:
      - ./build-alpine/linux/install:/install:ro
    working_dir: /install
    entrypoint: ['/bin/bash', '-c']
    command:
      - |
        apt install ./omnirefl*.deb &&
        mkdir -p /tmp/test/build && cd /tmp/test/build
        cp -r /usr/share/omnirefl/tests/* ../
        cmake .. -GNinja &&
        mkdir -p /build/test/ubuntu-22 &&
        ctest . --output-junit /build/test/ubuntu-22/results.xml \
          -V | tee /build/test/ubuntu-22/results.log \
        && apt remove -y omnirefl

