FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# C++ dev tools & libs
RUN apt-get update && \
    apt-get install -y build-essential gcc ninja-build cmake \
    libgtest-dev \
    neovim && \
    apt-get clean

WORKDIR /app

CMD ["bash"]
