
// todo:
// - ast caching (?)
// - run queries on the ast and output the code

// todo:
// #include "tool/..." // - tool related code
// #include "refl/..." // - reflection related code
// #include "plugin/..." // - plugin related code

#include "tool/reflection.hpp"
#include "tool/tool_template.hpp"
#include "tool/util.hpp"

#include <fmt/format.h>
#include <tl/expected.hpp>

#include <algorithm>
#include <fstream>
#include <set>
#include <vector>

namespace {

// todo: move to another file
struct emit_code_t {
  struct options {
    // todo: options
  };

  // todo: do I need this?
  struct reflection_data {
    // used to generate `omni::reflected_t<user_type>` specializations
    struct reflected_type {
      // fully namespace-qualified type
      std::string name;
      std::vector<std::string> field_names;
    };

    // todo: profile and optimize (std::set -> std::vector)
    // list of unique header paths (non-reflection)
    std::set<std::string> includes;

    // list of unique header paths or reflected types' headers
    std::set<std::filesystem::path> refl_includes;

    // list of unique header paths or reflected implementations' headers
    std::set<std::string> refl_impl_includes;

    // list of unique reflected types
    std::set<reflected_type,
      decltype([](const reflected_type &lhs, const reflected_type &rhs) -> bool {
        // types are unique
        return lhs.name < rhs.name;
      })>
      reflected_types;

    // list of unique reflected call function signatures
    std::vector<tool::refl::func_signature> reflected_calls;
  };

  static tl::expected<reflection_data, std::string> prepare_input(
    tool::refl::context ctx) noexcept {
    tl::expected<reflection_data, std::string> r{tl::in_place};
    // todo: validate input

    r->includes = {std::make_move_iterator(ctx.std_includes.begin()),
      std::make_move_iterator(ctx.std_includes.end())};

    for (const auto &[nm_qual_type, fields] : ctx.reflected_types) {
      const auto definition = ctx.definitions.find(nm_qual_type);
      if (definition == ctx.definitions.cend())
        return tl::unexpected(fmt::format("no definition for reflected type {}", nm_qual_type));

      r->refl_includes.emplace(definition->second.source_file);
      r->reflected_types.insert({
        .name = nm_qual_type,
        .field_names =
          [](const std::vector<tool::refl::struct_field_data> &fields) -> std::vector<std::string> {
          std::vector<std::string> r;
          r.reserve(fields.size());
          std::transform(fields.cbegin(),
            fields.cend(),
            std::back_inserter(r),
            [](const tool::refl::struct_field_data &fd) { return fd.name; });
          return r;
        }(fields),
      });
    }

    for (const auto &nm_qual_type : ctx.reflected_implementations) {
      const auto definition = ctx.definitions.find(nm_qual_type);
      if (definition == ctx.definitions.cend())
        return tl::unexpected(
          fmt::format("no definition for reflected implementation type {}", nm_qual_type));
      const auto &sf = definition->second.source_file;
      if (!r->refl_includes.contains(sf))
        r->refl_impl_includes.emplace(sf);
    }

    std::set unique_func_signatures{std::make_move_iterator(ctx.reflected_calls.begin()),
      std::make_move_iterator(ctx.reflected_calls.end()),
      [](const tool::refl::func_signature &lhs, const tool::refl::func_signature &rhs) -> bool {
        // because c++ std is UGLEEEEEEE
        return std::lexicographical_compare(lhs.args.cbegin(),
          lhs.args.cend(),
          rhs.args.cbegin(),
          rhs.args.cend(),
          [](const tool::refl::function_signature_arg &lhs,
            const tool::refl::function_signature_arg &rhs) -> bool {
            return lhs.cvr_qualified_type < rhs.cvr_qualified_type;
          });
      }};

    r->reflected_calls = {std::make_move_iterator(unique_func_signatures.begin()),
      std::make_move_iterator(unique_func_signatures.end())};

    return r;
  }

  tl::expected<void, std::string>
    operator()(options, std::ostream &os, const reflection_data &data) const {
    os << "// This file has been generated by omnirefl tool (todo: timestamp, data, etc)."
          "\n// Do not modify this file manually.\n";

    os << "\n#include <omnirefl/refl.hpp>"
          "\n"
          "\n#include <tuple>"
          "\n#include <utility>";

    // todo: source paths should not be absolute.
    //    use `options::target_include_paths` to resolve relative paths.
    os << "\n\n// Headers of reflected types";
    for (const std::filesystem::path &p : data.refl_includes)
      os << fmt::format("\n#include \"{}\"", p.string());

    os << "\n\n// Headers of reflected implementations";
    for (const auto &p : data.refl_impl_includes)
      os << fmt::format("\n#include \"{}\"", p);

    os << "\n\n// Other headers";
    for (const auto &p : data.includes)
      os << fmt::format("\n#include <{}>", p);

    os << "\n\n// Generated specializations for types' reflection";
    os << "\n#ifndef OMNI_DEFINE_NAME_FUNC"
          "\n#  define OMNI_DEFINE_NAME_FUNC(STR) \\"
          "\nconstexpr static auto name() noexcept -> const char(&)[sizeof(STR)] { return STR; }"
          "\n#endif\n";
    for (const auto &refl_type : data.reflected_types) {
      os << fmt::format(
        // todo: annotate the header file where this type was included from
        "\ntemplate <>"
        "\nstruct omni::reflected_t<{type_name}>{{"
        "\n  using type = {type_name};"
        "\n"
        "\n  // fields meta types declarations"
        "{field_decls}"
        "\n"
        "\n  using fields_t = std::tuple<"
        "\n{field_names}"
        "\n  >;"
        "\n"
        "\n  constexpr reflected_binding<reflected_t<type>, type> operator()(type &t) const noexcept {{return {{t}};}}"
        "\n  constexpr reflected_binding<reflected_t<type>, const type> operator()(const type &t) const noexcept {{return {{t}};}}"
        "\n}};\n",
        fmt::arg("type_name", refl_type.name),
        fmt::arg("field_decls",
          fmt::join(
            util::with_fmt_rng{
              .value = std::cref(refl_type.field_names),
              .format =
                [](const auto &field_name, fmt::format_context &ctx) {
                  return fmt::format_to(ctx.out(),
                    "\n  struct {field_name}_t {{"
                    "\n    OMNI_DEFINE_NAME_FUNC(\"{field_name}\")"
                    "\n    constexpr static auto get_value(const type &t) noexcept"
                    "\n    -> const decltype(t.{field_name})& {{"
                    "\n      return t.{field_name};"
                    "\n    }}"
                    "\n"
                    "\n    template <typename V>"
                    "\n    void set_value(type &t, V &&v) {{"
                    "\n      t.{field_name} = std::forward<V>(v);"
                    "\n    }}"
                    "\n  }} constexpr static {field_name}{{}};",
                    fmt::arg("field_name", field_name));
                },
            },
            "\n")),
        fmt::arg("field_names",
          fmt::join(
            util::with_fmt_rng{
              .value = std::cref(refl_type.field_names),
              .format =
                [](const auto &field_name, fmt::format_context &ctx) {
                  return fmt::format_to(ctx.out(),
                    "    {field_name}_t",
                    fmt::arg("field_name", field_name));
                },
            },
            ",\n")));
    }
    os << "\n#undef OMNI_DEFINE_NAME_FUNC\n";

    os << "\n// Generated implementations for reflected calls";
    for (const tool::refl::func_signature &func_sig : data.reflected_calls) {
      // refactorme: this formatted printing doesn't really look cleaner than handwritten loops
      // fixme: otherwise lambda does not compile
      size_t arg_index = 0;
      os << fmt::format(
        "\ntemplate<>"
        "\nvoid omni::reflected_call_t::_call_impl("
        "\n  {params}) {{"
        "\n  {invoke}({args});"
        "\n}}",
        // refactorme: consider using fold to a substring instead
        fmt::arg("params",
          fmt::join(
            util::with_fmt_rng{
              // fixme: .value = util::indexed(fund_sig.args),
              .value = std::cref(func_sig.args),
              .format =
                [&arg_index](const tool::refl::function_signature_arg &f_arg,
                  fmt::format_context &ctx) {
                  std::string param_name = 0 == arg_index //
                    ? std::string("impl")
                    : std::to_string(arg_index);
                  ++arg_index;
                  return fmt::format_to(ctx.out(),
                    "{nm_qual_type} {const}{ref}_{param_name}",
                    fmt::arg("nm_qual_type", f_arg.nm_qual_type),
                    fmt::arg("const", f_arg.is_const ? "const" : ""),
                    fmt::arg("ref",
                      [](tool::refl::reference_type r) -> std::string_view {
                        switch (r) {
                        case tool::refl::reference_type::ref_lval:
                          return "&";
                        case tool::refl::reference_type::ref_rval:
                          return "&&";
                        case tool::refl::ref_none:
                          return "";
                        }
                        return "/*unresolved_reference_type*/";
                      }(f_arg.ref_type)),
                    fmt::arg("param_name", std::move(param_name)));
                },
            },
            ",\n  ")),
        // refactorme: `util::indexed(util::sliced({1}, func_sig.args))`
        fmt::arg("invoke",
          [](const tool::refl::function_signature_arg &arg_impl) -> std::string_view {
            return tool::refl::reference_type::ref_rval == arg_impl.ref_type //
              ? "std::move(_impl)"
              : "_impl";
          }(func_sig.args.front())),
        // refactorme: this is outrigth ugly
        fmt::arg("args", [](auto begin, auto end) -> std::string {
          if (begin == end)
            return "";

          std::stringstream ss;
          size_t i = 1;
          if (tool::refl::reference_type::ref_rval == begin->ref_type)
            ss << "std::move(_" << i << ")";
          else
            ss << "_" << i;

          while (++begin != end) {
            ++i;
            if (tool::refl::reference_type::ref_rval == begin->ref_type)
              ss << ", std::move(_" << i << ")";
            else
              ss << ", _" << i;
          }
          return ss.str();
        }(std::next(func_sig.args.cbegin()), func_sig.args.cend())));
    }

    os << '\n';
    return {};
  }
} const inline emit_code{};

} // namespace

// refactorme: main should only contain a tool invocation code,
// allowing to configure specific things:
// - matchers
// - output to file
// - what else
int main(int argc, char **argv) {
  // disregard this comment. I'm experimenting with interface here
  /*
   *  std::pair{argc, argv}
   *  >>= chained
   *      | applied(tool::parse_cli) // -> cli_opts
   *      // will bind the result to the left
   *      | with_result_l([](const auto &cli) {
   *          return tool::load_compilation_db(cli->compilation_db_path);
   *      }) // -> tuple<std::unique_ptr<CompilationDb>, cli_opts>
   *      | with_result_l([](const auto &db, const auto &...) { return db.getAllFiles(); }
   *          | filtered(empty_str)
   *          | converted(to_std_path))
   *      // -> tuple<vector<path>, unique_ptr<CompilationDb>, cli_opts>
   *      | applied([](auto sources, auto db, auto cli_opts) {
   *          return tuple{map([&db](auto src) {
   *              auto opts = db.compileOptions(src);
   *              return tuple{std::move(src), std::move(opts)},
   *          stdd::move(db),
   *          std::move(cli_opts),
   *          };
   *      }) // -> tuple<vector<tuple<path, compile_options>>, db, cli>
   *      | applied([](auto compiled_sources, auto ... rest) {
   *          return tuple{
   *              foldl(tu_context{},
   *              // this actually requies `applied` but a little bit different
   *              [](auto ctx, const auto &src_path, const auto &compile_options){
   *                  auto delta_ctx = match_ast(src_path, compile_options);
   *                  return update(ctx, std::move(delta_ctx));
   *              }, compiled_sources),
   *              std::move(rest)...};
   *      }) // -> tuple<tu_context, db, cli>
   *      | // todo: validate accumulated tu_context and generate the .cpp file
   */

  auto cli = tool::parse_cli(argc, argv);
  if (!cli) {
    llvm::errs() << cli.error();
    return -1;
  }

  auto compilation_db = tool::load_compilation_db(cli->compilation_db_path);
  if (!compilation_db) {
    llvm::errs() << std::move(compilation_db).error();
    llvm::errs() << cli->compilation_db_path << '\n';
    return -1;
  }

  auto db_sources = util::to_std_paths((*compilation_db)->getAllFiles());
  if (!db_sources) {
    llvm::errs() << std::move(db_sources).error();
    llvm::errs() << cli->compilation_db_path << '\n';
    return -1;
  }

  const auto filtered_sources = tool::filter_db_sources(
    {
      .specified_sources = cli->sources,
      .excluded_folders = cli->excluded_folders,
    },
    *db_sources);
  if (!filtered_sources) {
    llvm::errs() << std::move(filtered_sources).error();
    llvm::errs() << cli->compilation_db_path << '\n';
    return -1;
  }

  // llvm doesn't know how to work with std::filesystem::path (so is fmt)
  // What a rotten way to die...
  const auto str_sources =
    [](const std::vector<std::filesystem::path> &paths) -> std::vector<std::string> {
    std::vector<std::string> res;
    res.reserve(paths.size());
    for (const auto &p : paths)
      res.push_back(p.string());
    return res;
  }(*filtered_sources);
  // todo: use verbosity option
  fmt::println("Filtered sources: [{}]", fmt::join(str_sources, ", "));

  // todo: fold
  tool::refl::context ctx{};
  size_t processing = 0;
  // todo: util::indexed(*filtered_sources)
  for (const auto &src : *filtered_sources) {
    fmt::println("[{}/{}] building AST of file: {}\t\r",
      ++processing,
      filtered_sources->size(),
      src.string());

    auto ast = tool::parse_ast({
      .resource_dir = cli->resource_dir,
      .source = src,
      .db = **compilation_db,
    });
    if (!ast) {
      llvm::errs() << ast.error();
      return -1;
    }

    // refactorme: (?) list of template arguments here will cause a lot of problems, because the
    // order must be specified exactly like in other places
    auto matches = tool::match_ast(
      std::tuple{
        tool::refl::matches::reflected_type{},
        tool::refl::matches::reflected_call{},
      },
      **ast);
    if (!matches) {
      llvm::errs() << matches.error();
      return -1;
    }

    auto ctx_delta = util::foldl(
      [&ast = **ast](tl::expected<tool::refl::context, std::string> ctx, const auto &match) {
        if (ctx)
          return tool::refl::resolve_matched_node(std::move(ctx).value(), ast, match);
        return ctx;
      },
      tl::expected<tool::refl::context, std::string>{tl::in_place})(std::move(matches).value());

    if (!ctx_delta) {
      llvm::errs() << ctx_delta.error();
      return -1;
    }

    if (auto updated = update(std::move(ctx), std::move(ctx_delta).value()); updated) {
      ctx = std::move(updated).value();
    } else {
      llvm::errs() << updated.error();
      return -1;
    }
  }

  auto validated_reflection_data = emit_code_t::prepare_input(std::move(ctx));
  if (!validated_reflection_data) {
    llvm::errs() << validated_reflection_data.error();
    return -1;
  }

  fmt::println("Generating file: {}\n", cli->output_file.string());
  std::ofstream f{cli->output_file, std::ios::binary};
  if (const auto res = emit_code(
        {
          // todo: options
        },
        f,
        *validated_reflection_data);
      !res) {
    llvm::errs() << res.error() << '\n';
    return -1;
  };
  return 0;
}
