
#include "tool/header_mode/transforms.h"
#include "tool/util.hpp"

#include <fmt/core.h>

namespace {

using namespace tool::header_mode;

auto fmt_reflected_field(std::string_view field_name,
  fmt::format_context &ctx) {
  return fmt::format_to(ctx.out(),
    // ad hoc: manual offset
    R"(  struct {field_name}_t {{
    OMNI_DEFINE_NAME_FUNC("{field_name}")
    constexpr static auto get_value(const type &t) noexcept
      -> const decltype(t.{field_name})& {{
      return t.{field_name};
    }}

    template <typename V>
    static void set_value(type &t, V &&v) {{
      t.{field_name} = std::forward<V>(v);
    }}
  }} constexpr static {field_name}{{}};)",
    fmt::arg("field_name", field_name));
}

auto fmt_indexed_reflected_field(std::string_view field_name,
  fmt::format_context &ctx) {
  return fmt::format_to(ctx.out(),
    // ad hoc: manual offset
    R"(  struct {field_name}_t {{
    OMNI_DEFINE_NAME_FUNC("{field_name}")
    template <typename T>
    constexpr static auto get_value(const T &t) noexcept
      -> const decltype(t.{field_name})& {{
      return t.{field_name};
    }}

    template <typename T, typename V>
    static void set_value(T &t, V &&v) {{
      t.{field_name} = std::forward<V>(v);
    }}
  }} constexpr static {field_name}{{}};)",
    fmt::arg("field_name", field_name));
}

auto fmt_forward_declaration_specialization(
  const codegen::forward_declarable &refl_type,
  fmt::context &ctx) {
  using namespace std::string_view_literals;

  return fmt::format_to(ctx.out(),
    R"(template <typename T>
struct _reflected<{type_tag} {type_name}, T> {{
  static_assert(std::is_same<{type_tag} {type_name}, T>::value,
    "omnirefl: unexpected types mismatch, try regenerating");
  using type = T;

  // fields meta types declarations
{reflected_fields}

  using fields_t = std::tuple<
{field_names}
  >;

  constexpr reflected_binding<type, fields_t> operator()(type &t) const noexcept {{
    return {{t}};
  }}

  constexpr reflected_binding<const type, fields_t> operator()(const type &t) const noexcept {{
    return {{t}};
  }}
}};)",
    fmt::arg("type_tag", refl_type.is_class ? "class"sv : "struct"sv),
    fmt::arg("type_name", refl_type.nm_qual_type),
    fmt::arg("reflected_fields", //
      util::join(refl_type.fields, "\n\n", fmt_reflected_field)),
    fmt::arg("field_names", util::join(refl_type.fields, ",\n", [] {
      // ad hoc: manual offset
      return "    {}_t";
    })));
}

auto fmt_indexed_specialization(size_t index,
  const std::vector<std::string> &field_names,
  fmt::context &ctx) {
  using namespace std::string_view_literals;

  return fmt::format_to(ctx.out(),
    R"(template <>
struct _indexed_reflected<{index}> {{

  // fields meta types declarations
{indexed_reflected_fields}

  using fields_t = std::tuple<
{field_names}
  >;

  template <typename T>
  constexpr reflected_binding<T, fields_t> operator()(T &t) const noexcept {{
    return {{t}};
  }}

  template <typename T>
  constexpr reflected_binding<const T, fields_t> operator()(const T &t) const noexcept {{
    return {{t}};
  }}
}};)",
    fmt::arg("index", index),
    fmt::arg("indexed_reflected_fields", //
      util::join(field_names, "\n\n", fmt_indexed_reflected_field)),
    fmt::arg("field_names",
      util::join(field_names,
        ",\n",
        // ad hoc: manual offset
        [] { return "    {}_t"; })));
}

auto fmt_forward_declaration(const codegen::forward_declarable &t,
  fmt::context &ctx) {
  std::vector<std::string_view> namespaces;
  std::string_view name = t.nm_qual_type;
  for (size_t pos = name.find("::"); pos != name.npos; pos = name.find("::")) {
    namespaces.emplace_back(name.substr(0, pos));
    name = name.substr(pos + 2);
  }

  return fmt::format_to(ctx.out(),
    "{open_namespaces}\n{tag} {name};\n{close_namespaces}",
    fmt::arg("open_namespaces",
      util::join(namespaces, "\n", [] { return "namespace {} {{"; })),
    fmt::arg("tag", t.is_class ? "class" : "struct"),
    fmt::arg("name", name),
    fmt::arg("close_namespaces",
      util::join(namespaces, "\n", [] { return "}} // namespace {}"; })));
}

} // namespace

namespace tool::header_mode {

tl::expected<void, std::string> codegen::emit_reflection_header_file(options,
  std::ostream &os,
  const reflection_data &data) {
  using namespace std::string_view_literals;

  os << fmt::format(
    R"(// This header has been generated by omnirefl tool (todo: timestamp, data, etc).
// Do not modify this file manually.

// Forward declarations of reflected types
{forward_declarations}

// todo: 
//   these headers might show as unused.
//   consider writing own implementations instead of including these
#include <tuple>
#include <type_traits>
#include <utility>

namespace omni {{

template <typename, typename>
struct reflected_binding;

namespace detail {{
namespace {{

template <int>
struct _indexed_reflected;

template <typename T, typename>
struct _reflected;

// macro for static member function definition to
// to reduce boilerplate ... in a boilerplate
#  define OMNI_DEFINE_NAME_FUNC(STR) \
constexpr static auto name() noexcept -> const char(&)[sizeof(STR)] {{ return STR; }}

// Generated reflection specializations for forward-declared types
{forward_declaration_specializations}

// Generated reflection specializations for indexed types
{indexed_specializations}

}} // namespace
}} // namespace detail
}} // namespace omni

#define OMNI_INCLUDED_GENERATED_REFLECTION_HEADER
)",
    fmt::arg("forward_declarations",
      util::join(data.forward_declarable_types,
        "\n\n",
        ::fmt_forward_declaration)),
    fmt::arg("forward_declaration_specializations",
      util::join(data.forward_declarable_types,
        "\n\n",
        ::fmt_forward_declaration_specialization)),
    fmt::arg("indexed_specializations",
      util::join(data.reflected_indexed_types,
        "\n\n",
        [](const auto &key_val, fmt::context &ctx) {
          const auto &[index, fields] = key_val;
          return ::fmt_indexed_specialization(index, fields, ctx);
        })));

  return {};
}

} // namespace tool::header_mode
