// this will enable definitions for rapidyaml, since it has been amalgamated to a single header
// it has to be defined before the headers that use it's interface
#define RYML_SINGLE_HDR_DEFINE_NOW
#include <ryml/ryml.hpp>

#include "foo.h"

#include <omnirefl/refl.h>

#include <gtest/gtest.h>

namespace {

// fixme: `std::vector<foo>` is a dependent field in `with_vector`, but as of this writing the
// implementation doesn't detect it and `foo` serialization is not generated... (it is generated by
// `deserialize.to<bar>` though)
[[maybe_unused]] void _force_gen() {
  // (void)omni::deserialize.to<foo>(ryml::ConstNodeRef{});
}
// todo: use benchmarking
// todo: use codogen
TEST(ryml, deserialize_bar) {
  // todo: separate function to be also used for benchmarking
  // do not call `<foo>` serialization anywhere in this test, since this test is intended to check
  // for nested generation
  const auto res = omni::deserialize.to<bar>(ryml::parse_in_arena( //
    R"({"d": 23.42, "f": {"a": "oceanic", "b": 815}})"));
  ASSERT_TRUE(res) << res.error();
  const bar &b = *res;
  ASSERT_EQ(b.d, 23.42);
  ASSERT_EQ(b.f.a, "oceanic");
  ASSERT_EQ(b.f.b, 815);
  // todo: test for errors
}

// todo: make another nested type that is not instantiated by other functions
TEST(ryml, deserialize_with_vector) {
  // todo: empty vector
  // todo: invalid json
  // todo: function to init vector and json from N arg
  // todo: standalone function to also be used for benchmarking
  const auto res = omni::deserialize.to<with_vector>(ryml::parse_in_arena(
    R"({"vec": 
    [
      {"a": "a_0", "b": 0},
      {"a": "a_1", "b": 1},
      {"a": "a_2", "b": 2},
    ]})"));
  ASSERT_TRUE(res) << res.error();
  for (size_t i = 0; i < res->vec.size(); ++i) {
    const foo expected = foo{"a_" + std::to_string(i), int(i)};
    ASSERT_EQ(expected.a, res->vec[i].a);
    ASSERT_EQ(expected.b, res->vec[i].b);
  }
}

// fixme: older systems don't have support for c++17
// // todo: enable when implemented
// TEST(ryml, DISABLED_deserialize_with_variant) {
//   const auto res = omni::deserialize.to<dependent_types_variant::s>(ryml::parse_in_arena( //
//     R"({"v": {"b": 108}})"));
//   ASSERT_TRUE(res) << res.error();
//   // todo: implement deserialization for std::variant and check
// }

// todo: test and benchmark serialization
//   - user-defined serialization function
//      - for nested fields
//   - same type (from `T` to `T`)
//   - fundamental types
//   - containers (to a reasonable extent)
//   - local and unnamed structs (need to implement)
//   - aliased fields

// int main() {
//   // todo: use `omni::deserialize` for fundamental types
//   {
//     bool v;
//     if (const auto res = deserialize(ryml::parse_in_arena(R"({"oceanic": 815})")["oceanic"], v);
//         !res)
//       std::cout << res.error() << '\n';
//     else {
//       std::cout << v << '\n' << *res.value() << '\n';
//     }
//   }
//
//   {
//     std::vector<int> v;
//     if (const auto res =
//           deserialize(ryml::parse_in_arena(R"({"oceanic": [4, 8, 15, 16, 23, 42]})")["oceanic"],
//           v);
//         !res)
//       std::cout << res.error() << '\n';
//     else {
//       for (int i : v)
//         std::cout << i << ' ';
//       std::cout << '\n';
//     }
//   }
//
//   {
//     struct {
//       std::string a;
//       int b;
//     } oceanic;
//
//     // todo: meta stuff
//     object<int, std::string> _oceanic{{
//       {"b", &oceanic.b},
//       {"a", &oceanic.a},
//     }};
//
//     if (const auto res = deserialize(
//           // todo: handle invalid case `{"oceanic": {108, 815}}`, parser doesn't catch that
//           ryml::parse_in_arena(R"({"a": "oceanic", "b": 815})"),
//           _oceanic);
//         !res)
//       std::cout << res.error() << '\n';
//     else {
//       std::cout << oceanic.a << ' ' << oceanic.b << '\n';
//     }
//   }
//
//   return 0;
// }
} // namespace

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  // todo: ::benchmark::Initialize(&argc, argv);
  return RUN_ALL_TESTS();
}
