#include "tool/emit_code.hpp"

#include "tool/util.hpp"

#include <fmt/base.h>

tl::expected<codegen::reflection_data, std::string> codegen::prepare_input(
  tool::refl::context ctx) noexcept {
  tl::expected<reflection_data, std::string> r{tl::in_place};
  // todo: validate input

  r->includes = {std::make_move_iterator(ctx.std_includes.begin()),
    std::make_move_iterator(ctx.std_includes.end())};

  for (const auto &[nm_qual_type, fields] : ctx.reflected_types) {
    const auto _definition = ctx.definitions.find(nm_qual_type);
    if (_definition == ctx.definitions.cend())
      return tl::unexpected(fmt::format("no definition for reflected type {}", nm_qual_type));

    const auto &[_, definition] = *_definition;
    using td_flags = tool::refl::type_definition_flags;
    // todo: consider validating the flags beforehand, so all the info can be reported at once.
    if (td_flags::local & definition.definition_flags)
      // todo: additional info
      return tl::unexpected(fmt::format("local types are not supported"));

    if (td_flags::in_cpp & definition.definition_flags) {
      return tl::unexpected(
        fmt::format("types defined in .cpp are not supported: {}", nm_qual_type));
    }

    r->refl_includes.emplace(definition.source_file);
    r->reflected_types.insert({
      .name = nm_qual_type,
      .field_names =
        [](const std::vector<tool::refl::struct_field_data> &fields) -> std::vector<std::string> {
        std::vector<std::string> r;
        r.reserve(fields.size());
        std::transform(fields.cbegin(),
          fields.cend(),
          std::back_inserter(r),
          [](const tool::refl::struct_field_data &fd) { return fd.name; });
        return r;
      }(fields),
      .is_class = definition.is_class,
    });
  }

  for (const auto &nm_qual_type : ctx.reflected_implementations) {
    const auto definition = ctx.definitions.find(nm_qual_type);
    if (definition == ctx.definitions.cend())
      return tl::unexpected(
        fmt::format("no definition for reflected implementation type {}", nm_qual_type));
    const auto &sf = definition->second.source_file;
    if (!r->refl_includes.contains(sf))
      r->refl_impl_includes.emplace(sf.string());
  }

  std::set unique_func_signatures{std::make_move_iterator(ctx.reflected_calls.begin()),
    std::make_move_iterator(ctx.reflected_calls.end()),
    [](const tool::refl::func_signature &lhs, const tool::refl::func_signature &rhs) -> bool {
      // because c++ std is UGLEEEEEEE
      return std::lexicographical_compare(lhs.args.cbegin(),
        lhs.args.cend(),
        rhs.args.cbegin(),
        rhs.args.cend(),
        [](const tool::refl::function_signature_arg &lhs,
          const tool::refl::function_signature_arg &rhs) -> bool {
          return std::tie(lhs.nm_qual_type, lhs.is_const, lhs.ref_type)
            < std::tie(rhs.nm_qual_type, rhs.is_const, rhs.ref_type);
        });
    }};

  r->reflected_calls = {std::make_move_iterator(unique_func_signatures.begin()),
    std::make_move_iterator(unique_func_signatures.end())};

  return r;
}

tl::expected<void, std::string>
  codegen::emit_code(options, std::ostream &os, const reflection_data &data) {
  using namespace std::string_view_literals;

  os << "// This file has been generated by omnirefl tool (todo: timestamp, data, etc)."
        "\n// Do not modify this file manually.\n";

  os << "\n#include <omnirefl/refl.hpp>"
        "\n"
        "\n#include <tuple>"
        "\n#include <utility>";

  // todo: source paths should not be absolute.
  //    use `options::target_include_paths` to resolve relative paths.
  os << "\n\n// Headers of reflected types";
  for (const std::filesystem::path &p : data.refl_includes)
    os << fmt::format("\n#include \"{}\"", p.string());

  os << "\n\n// Headers of reflected implementations";
  for (const auto &p : data.refl_impl_includes)
    os << fmt::format("\n#include \"{}\"", p);

  os << "\n\n// Other headers";
  for (const auto &p : data.includes)
    os << fmt::format("\n#include <{}>", p);

  os << "\n\n// Generated specializations for types' reflection";
  os << "\n#ifndef OMNI_DEFINE_NAME_FUNC"
        "\n#  define OMNI_DEFINE_NAME_FUNC(STR) \\"
        "\nconstexpr static auto name() noexcept -> const char(&)[sizeof(STR)] { return STR; }"
        "\n#endif\n";
  for (const auto &refl_type : data.reflected_types) {
    os << fmt::format(
      // todo: annotate the header file where this type was included from
      "\ntemplate <>"
      "\nstruct omni::reflected_t<{type_tag} {type_name}>{{"
      // todo: this will give a warning
      "\n  using type = {type_tag} {type_name};"
      "\n"
      "\n  // fields meta types declarations"
      "{field_decls}"
      "\n"
      "\n  using fields_t = std::tuple<"
      "\n{field_names}"
      "\n  >;"
      "\n"
      "\n  constexpr reflected_binding<reflected_t<type>, type> operator()(type &t) const noexcept {{return {{t}};}}"
      "\n  constexpr reflected_binding<reflected_t<type>, const type> operator()(const type &t) const noexcept {{return {{t}};}}"
      "\n}};\n",
      fmt::arg("type_tag", refl_type.is_class ? "class"sv : "struct"sv),
      fmt::arg("type_name", refl_type.name),
      fmt::arg("field_decls",
        fmt::join(
          util::with_fmt_rng{
            .value = std::cref(refl_type.field_names),
            .format =
              [](const auto &field_name, fmt::format_context &ctx) {
                return fmt::format_to(ctx.out(),
                  "\n  struct {field_name}_t {{"
                  "\n    OMNI_DEFINE_NAME_FUNC(\"{field_name}\")"
                  "\n    constexpr static auto get_value(const type &t) noexcept"
                  "\n    -> const decltype(t.{field_name})& {{"
                  "\n      return t.{field_name};"
                  "\n    }}"
                  "\n"
                  "\n    template <typename V>"
                  "\n    static void set_value(type &t, V &&v) {{"
                  "\n      t.{field_name} = std::forward<V>(v);"
                  "\n    }}"
                  "\n  }} constexpr static {field_name}{{}};",
                  fmt::arg("field_name", field_name));
              },
          },
          "\n")),
      fmt::arg("field_names",
        fmt::join(
          util::with_fmt_rng{
            .value = std::cref(refl_type.field_names),
            .format =
              [](const auto &field_name, fmt::format_context &ctx) {
                return fmt::format_to(ctx.out(),
                  "    {field_name}_t",
                  fmt::arg("field_name", field_name));
              },
          },
          ",\n")));
  }
  os << "\n#undef OMNI_DEFINE_NAME_FUNC\n";

  os << "\n// Generated implementations for reflected calls";
  for (const tool::refl::func_signature &func_sig : data.reflected_calls) {
    // refactorme: this formatted printing doesn't really look cleaner than handwritten loops
    // fixme: otherwise lambda does not compile
    size_t arg_index = 0;
    os << fmt::format(
      "\n"
      "\ntemplate<>"
      "\nvoid omni::reflected_call_t::_call_impl("
      "\n  {params}) {{"
      "\n  {invoke}({args});"
      "\n}}",
      // refactorme: consider using fold to a substring instead
      fmt::arg("params",
        fmt::join(
          util::with_fmt_rng{
            // fixme: .value = util::indexed(fund_sig.args),
            .value = std::cref(func_sig.args),
            .format =
              [&arg_index](const tool::refl::function_signature_arg &f_arg,
                fmt::format_context &ctx) {
                std::string param_name = 0 == arg_index //
                  ? std::string("impl")
                  : std::to_string(arg_index);
                ++arg_index;
                return fmt::format_to(ctx.out(),
                  "{nm_qual_type} {const}{ref}_{param_name}",
                  fmt::arg("nm_qual_type", f_arg.nm_qual_type),
                  fmt::arg("const", f_arg.is_const ? "const" : ""),
                  fmt::arg("ref",
                    [](tool::refl::reference_type r) -> std::string_view {
                      switch (r) {
                      case tool::refl::reference_type::ref_lval:
                        return "&";
                      case tool::refl::reference_type::ref_rval:
                        return "&&";
                      case tool::refl::ref_none:
                        return "";
                      }
                      return "/*unresolved_reference_type*/";
                    }(f_arg.ref_type)),
                  fmt::arg("param_name", std::move(param_name)));
              },
          },
          ",\n  ")),
      // refactorme: `util::indexed(util::sliced({1}, func_sig.args))`
      fmt::arg("invoke",
        [](const tool::refl::function_signature_arg &arg_impl) -> std::string_view {
          return tool::refl::reference_type::ref_rval == arg_impl.ref_type //
            ? "std::move(_impl)"
            : "_impl";
        }(func_sig.args.front())),
      // refactorme: this is outrigth ugly
      fmt::arg("args", [](auto begin, auto end) -> std::string {
        if (begin == end)
          return "";

        std::stringstream ss;
        size_t i = 1;
        if (tool::refl::reference_type::ref_rval == begin->ref_type)
          ss << "std::move(_" << i << ")";
        else
          ss << "_" << i;

        while (++begin != end) {
          ++i;
          if (tool::refl::reference_type::ref_rval == begin->ref_type)
            ss << ", std::move(_" << i << ")";
          else
            ss << ", _" << i;
        }
        return ss.str();
      }(std::next(func_sig.args.cbegin()), func_sig.args.cend())));
  }

  os << '\n';
  return {};
}
