if(NOT DEFINED CCDB_QUERY)
    message(FATAL_ERROR "CCDB_QUERY is required")
endif()
if(NOT DEFINED OMNIREFL)
    message(FATAL_ERROR "OMNIREFL is required")
endif()
if(NOT DEFINED COMP_DB)
    message(FATAL_ERROR "COMP_DB is required")
endif()
if(NOT DEFINED SOURCE)
    message(FATAL_ERROR "SOURCE is required")
endif()
if(NOT DEFINED OUTPUT_CONTAINS)
    message(FATAL_ERROR "OUTPUT_CONTAINS is required")
endif()
if(NOT DEFINED OUT)
    message(FATAL_ERROR "OUT is required")
endif()
if(NOT DEFINED RESOURCE_DIR)
    message(FATAL_ERROR "RESOURCE_DIR is required")
endif()
if(NOT DEFINED NO_ANNOTATIONS)
    set(NO_ANNOTATIONS 0)
endif()
if(NOT DEFINED LOG_LEVEL)
    set(LOG_LEVEL "info")
endif()
if(NOT DEFINED TIMINGS)
    set(TIMINGS 0)
endif()
if(NOT DEFINED MSVC_CXX23_PREVIEW_AD_HOC)
    set(MSVC_CXX23_PREVIEW_AD_HOC 0)
endif()

# Keep clangd diagnostics usable if generation fails: the source file is
# force-included with OUT, and a missing generated header poisons the LSP parse
# before the user has a chance to fix the actual omnirefl diagnostic.
file(WRITE "${OUT}"
    "// Placeholder generated by omnirefl CMake integration.\n"
    "// The real reflection header is generated by the .omni target.\n")

execute_process(
    COMMAND "${CCDB_QUERY}" "${COMP_DB}" "${SOURCE}" "${OUTPUT_CONTAINS}"
    RESULT_VARIABLE _ccdb_result
    OUTPUT_VARIABLE _compiler_command
    ERROR_VARIABLE _ccdb_err)

if(NOT 0 EQUAL _ccdb_result)
    message(FATAL_ERROR "${_ccdb_err}")
endif()

string(STRIP "${_compiler_command}" _compiler_command)
separate_arguments(_compiler_args UNIX_COMMAND "${_compiler_command}")

# clang-cl compile commands may contain a standalone `--` before the source.
# Clang's driver accepts that as command-line syntax, but the tooling invocation
# can treat it as an additional input and reject object-output flags as if
# multiple sources were passed. omnirefl already receives SOURCE separately, so
# the separator is not meaningful here.
list(REMOVE_ITEM _compiler_args "--")

if(MSVC_CXX23_PREVIEW_AD_HOC)
    # ad hoc: CMake can emit `/std:c++latest` for a target whose CXX_STANDARD is
    # 23 under MSVC. Clang's driver maps that to a newer cc1 mode, currently
    # C++26, which makes the tool-run parse disagree with the real target
    # intent. Keep the build-time ccdb_query flow, but normalize the single
    # standard flag before invoking omnirefl. This should move to cc1_flags.
    list(TRANSFORM _compiler_args REPLACE "^[-/]std:c\\+\\+latest$" "/std:c++23preview")
endif()

set(_omnirefl_args
    "${OMNIREFL}"
    --resource-dir "${RESOURCE_DIR}"
    --log-level "${LOG_LEVEL}"
    -o "${OUT}"
    -c "${SOURCE}")

if(NO_ANNOTATIONS)
    list(APPEND _omnirefl_args --no-annotations)
endif()
if(TIMINGS)
    list(APPEND _omnirefl_args --timings)
endif()

list(APPEND _omnirefl_args -- ${_compiler_args})

execute_process(
    COMMAND ${_omnirefl_args}
    RESULT_VARIABLE _omnirefl_result
    OUTPUT_VARIABLE _omnirefl_out
    ERROR_VARIABLE _omnirefl_err)

if(_omnirefl_out)
    message("${_omnirefl_out}")
endif()
if(_omnirefl_err)
    message("${_omnirefl_err}")
endif()

if(NOT 0 EQUAL _omnirefl_result)
    message(FATAL_ERROR "omnirefl failed with code ${_omnirefl_result}")
endif()
