name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    # todo: I am not sure this is a good way, but otherwise Remove Old Artifacts fails
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows]
        include:
          - os: linux
            run_tests: true
          - os: windows
            run_tests: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull build-alpine Image
        run: docker pull sergioeld/omnirefl-build-alpine:latest

      - name: Build omnirefl tool
        run: |
          docker compose run --rm build-${{ matrix.os }}

      - name: Run test
        if: ${{ matrix.run_tests }}
        run: docker compose run --rm build-tests-alpine

      # todo: packaging should not run on a merge request (? I think)
      - name: Package omnirefl tool
        run: |
          docker compose run --rm package-${{ matrix.os }}
      
      # todo: test results and benchmarks (for continious bench)
      # todo: separate packages for windows and linux
      - name: Remove Old Artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '90 seconds' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          skip-tags: true
          # ATTENTION: TODO: Ensure it doesn't remove artifacts from other jobs running in parallel
          skip-recent: 5

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: install-${{ matrix.os }}
          path: ./build-alpine/*/install/
          if-no-files-found: error

      # todo: separate these tests to another job
      # - name: Test Ubuntu 18
      #   run: |
      #     docker compose run --rm test-install-ubuntu-18

      # - name: Test Ubuntu 20
      #   run: |
      #     docker compose run --rm test-install-ubuntu-20

      # - name: Test Ubuntu 22
      #   run: |
      #     docker compose run --rm test-install-ubuntu-22

      # - name: Upload Test Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-result
      #     path: ./build-alpine/test/

  # todo: this should actually use the install package and test on several images
  test-linux:
    runs-on: ubuntu-latest
    needs: build-package
    strategy:
      fail-fast: false
      matrix:
        version: [ubuntu-18, ubuntu-20, ubuntu-22]

    steps:
      # needed only for `docker-compose.yml`
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull sergioeld/test-install-${{ matrix.version }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: install-linux
          path: ./build-alpine/

      - name: Run Test
        run: docker compose run --rm test-${{ matrix.version }}
      # todo: upload artifacts. If before merged, upload only if failed

  test-windows:
    runs-on: windows-2019
    needs: build-package
    strategy:
      fail-fast: false
      # matrix: #< todo

    steps:
      # needed only for `docker-compose.yml`
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull sergioeld/test-install-windows

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: install-windows
          path: ./build-alpine/

      - name: Run Test
        run: docker compose run --rm test-windows
      # todo: upload artifacts. If before merged, upload only if failed

# todo: windows
